type = "Component"
has_support_component = true
members_required = 2
description = """
- License transport between Odoo and Checkmk works
- Limitation in Checkmk works
- Sending license usage reports from Checkmk works
- The process means the sales team has significantly less work with license renewals
"""
