type = "Component"
display_name = "Vue Framework"
previous_name = "UI - Vue Framework"
has_support_component = true
members_required = 2
description = """
- The Vue framework, codebase and architecture
"""
