---
lint:
  aspects:
    - //bazel/tools:aspects.bzl%astrein
    - //bazel/tools:aspects.bzl%bandit
    - //bazel/tools:aspects.bzl%clang_tidy
    - //bazel/tools:aspects.bzl%ruff
    - //bazel/tools:aspects.bzl%semgrep
