[project]
name = "cmk-crypto"
version = "0.9.0"
dependencies = [
    "bcrypt",
    "cryptography",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"cmk.crypto" = ["py.typed"]

[tool.bandit]

[tool.black]
line_length = 100
quiet = true

[tool.isort]
profile = "black"
order_by_type = false
line_length = 100
py_version = 312

[tool.mypy]
explicit_package_bases = true
packages = ["cmk", "tests"]
strict = true
# Miscellaneous stuff not in --strict
disallow_any_decorated = true
disallow_any_explicit = true
# disallow_any_expr = true  -- TODO
disallow_any_generics = true
disallow_any_unimported = true
disallow_subclassing_any = true
no_implicit_optional = true
strict_optional = true
warn_unreachable = true
# hidden flags for PEP 688 compat, see https://github.com/python/mypy/issues/15313
disable_bytearray_promotion = true
disable_memoryview_promotion = true

[tool.pylint.format]
max-line-length = 100
persistent = "no"
score = "no"

[tool.pylint.messages_control]
disable = ["missing-function-docstring"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["cmk", "tests"]
addopts = "--doctest-modules --import-mode=importlib"
