[package]
name = "mk-sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiberius = { version = "0.12.2", features = [
    "winauth",
    "sql-browser-tokio",
    # "integrated-auth-gssapi",
] } # MS SQL


# need to compile OpenSSL. See:
# https://stackoverflow.com/questions/68871193/pkg-config-error-during-rust-cross-compilation
# https://github.com/rust-cross/rust-musl-cross/issues/44
openssl = { version = "0.10.73", features = ["vendored"] }
tokio = { version = "1.32.0", features = [
    "full",
    "rt",
    "rt-multi-thread",
    "macros",
] }
# tokio-rustls = "0.24.1"
tokio-util = { version = "0.7.8", features = ["compat"] }
anyhow = "1.0.75"
# tokio-macros = "2.1.0"
flexi_logger = { version = "0.27", default-features = false } # extension for log to allow log redirection
log = { version = "0.4" }
clap = { version = "<4.5", features = ["derive"] }            # needs rustc >= 1.74
yaml-rust2 = "0.8.0"
lazy_static = { version = "1.4" }
futures = { version = "0.3.25" }
# used for New Types derives, may be removed
derive_more = { version = "0.99", features = [
    "from",
    "display",
    "into",
    "default",
] }


[target.'cfg(windows)'.dependencies]
winreg = "0.52"
odbc-api = "7.2.3"

[dev-dependencies]
tempfile = { version = "3.10.1" }
assert_cmd = { version = "<2.0.14" } # needs rustc >= 1.73
