type = "Component"
display_name = "Site Management, OMD"
has_support_component = true
members_required = 3
description = """
- OMD site management mechanism
- Checkmk site and version management on the checkmk server
- OMD update: Everything from "omd update" to "cmk-update-config" until the update action of the plugins
  The plugins are part of the components owning the data being updated.
"""
