[project]
name = "cmk-agent-based"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.agent_based" = ["py.typed"]

[tool.bandit]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
# (not yet) implemented pylint rules under ruff (by the time writting...):
# | too-many-instance-attributes rule (R0902)
# | too-many-function-args            (E1121)
# | duplicate-code                    (R0801)
select = ["A", "ARG", "E", "F", "W", "C90", "PL", "RUF100", "SLF"]
ignore = [
  "PLR2004", # Magic value used in comparison, consider replacing `FOO` with a constant variable
]

[tool.ruff.lint.per-file-ignores]
# Explicit re-exports is fine in __init__.py, still a code smell elsewhere.
"__init__.py" = ["PLC0414"]

#[tool.ruff.lint.isort]
# see ruff.toml for the isort section

[tool.mypy]
enable_error_code = [
  "explicit-override",
  "ignore-without-code",
  "mutable-override",
  "possibly-undefined",
  # Neeeds to be investigated
  #"redundant-expr",
  "redundant-self",
  "truthy-bool",
  "truthy-iterable",
  "unimported-reveal",
  "unused-awaitable",
  "unused-ignore",
]
explicit_package_bases = true
packages = ["cmk", "tests"]
strict = true
# Miscellaneous stuff not in --strict
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_subclassing_any = true
no_implicit_optional = true
strict_optional = true
warn_unreachable = true
# hidden flags for PEP 688 compat, see https://github.com/python/mypy/issues/15313
disable_bytearray_promotion = true
disable_memoryview_promotion = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["cmk", "tests"]
addopts = "--doctest-modules --import-mode=importlib"
