# example of Check MK configuration file

# global must be presented
# IMPORTANT notes
# 1. use http://www.yamllint.com/ for example to validate your yamllint
# 2. Windows filenames contains backslash \, ergo you have to write either "c:\\windows" or 'c:\windows' 

global:
    # use name to have mor clear logs just for user
    # Descriptive name of the configuration file
    name: Config File Example from Check MK distribution

    # section may be fully disabled
    enabled: yes

    # Restrict access to certain IP addresses
    # If ipv6 is enabled, all listed ipv4 adresses are also accepted as
    # source adresses in their ipv6-mapped form. I.e. if
    # 192.168.56.0/24 is listed, connections from ::ffff:c0a8:3800/120
    # are also possible
    only_from:     # 127.0.0.1  192.168.56.0/24 ::1

    # Change port where the agent is listening ( default 6556 )
    port: 6556

    # New parameter
    lock: no # [-] use port exclusively by own process

    # Disable ipv6 support. By default, ipv4 is always supported
    # and ipv6 is enabled additionally if supported by the system.
    ipv6: no

    # Do only execute programs and scripts with
    # the following suffixes (in local and plugins).
    # Per default all extensions except txt and dir
    # are being executed.
    execute:  exe bat vbs cmd ps1

    # Run async scripts in parallel (to each other). Default is "sequential",
    # which means the scripts are run asynchronously to the agent itself but
    # one after the other. Setting this to parallel may improve the delay before
    # new data is reported but may also lead to the agent having more noticable
    # impact on the system performance
    async: yes

    # Restrict the following configuration variables
    # in [global] to the following hosts
    # ?????????
    host: 
        - '*'

    # Just output certain sections
    sections: check_mk mrpe skype spool plugins local winperf uptime systemtime df mem services msexch dotnet_clrmemory wmi_webservices wmi_cpuload ps fileinfo logwatch
    
    # forced to not use
    disabled_sections: openhardwaremonitor _logfiles winperf_xxx badname

    #realtime data description
    realtime:
        # specifies how long (in seconds) realtime updates are sent to
        # the last monitoring system that requested an update.
        # this should be longer than the request frequency (usually
        # one minute).
        # Please note that any new request cancels previous realtime
        # update schedules, so no more than one update is sent per second,
        # no matter if this timeout is "too high" or how many monitoring
        # systems are querying the agent.
        timeout: 90
        # enable/disable encryption of regular agent output (default: disabled) 
        # yes or no
        encrypted: no
        # passphrase for encrypted communication.
        passphrase: this is my password
        # which sections are realtime
        run: mem df winperf_processor

    # by default the agent flushes the socket for each agent section.
    # this is mostly for debugging purposes in case the agent is slow
    # to respond.
    # Disabling this may (very) slightly reduce network traffic.
    section_flush: no

    # -------------------------------------------------------------- 
    # Internal log of agent
    # Write a logfile for tackling down crashes of the agent
    logging:
        # folder with log file, empty is default which means '@data\log'
        location: 
        # name of file log, default is check_mk.log
        file : 
        # log in file also internal debug messages, recommended when we have problems
        # allowed no, yes and all. Default yes!
        debug: no
        # you may send logging messages in realtime in windows debug sink, default is yes
        windbg: yes

        # you may disable your eventlog ability
        eventlog: yes

ps:
    enabled: yes
    use_wmi: yes
    full_path: yes

winperf:
    enabled: yes

    # default value,  do not change it if do not know what are you douing
    exe: agent
    
    # better not change
    prefix: winperf

    # default value,  increase for heavy loaded machine
    timeout: 10
    
    # Select counters to extract. The following counters
    # are needed by checks shipped with check_mk.
    # id is OS is
    # name is check mk name, should be
    counters:
        - id: 234
          name: phydisk
        - id: 510
          name: if
        - id: 638
          name: tcp_conn
#        - id: 10332 
#          name: msx_queues
#        - id: Terminal Services
#          name: ts_sessions

logfiles:
    enabled: no
    ## Define textfiles to be monitored
    ## observer
    view:
        - name: My usual log for daily use with my friends # this is name of the check
          observe:
              - 'C:\tmp': # this is folder
                  # below list of file to view on location
                  - 'logfiles\message_*.log' 
                  - 'logfile\my*.log'
              - 'D:\log': #this is folder
                  - 'sample1.txt'
                  - 'sample2.txt'
              - 'c:\Windows\Logs\setupapi.log'
          patterns:
              ok:     'Successfully logged in*'
              crit:   'Error in*'
              warn:   'Unable to contact*'
              ignore: 'Backup * saved'
        - name: My special logs
          observe: 
              - 'C:\tmp\memo.udf':
          patterns:
              ok:     '*mail sent*'
              warn:   '*overdue*'
        - name: My interesting logs
          description: > 
                this is my description which I can add to almost any iten 
                item ib the config file and see it in the log
          observe: 
              - 'C:\tmp\memo.crit':
          # below is default
          rotated: no     
          context: yes      
          from_start: no
          patterns:
              ok:     '*mail sent*'
              warn:   '*overdue*'

fileinfo:
    path:
        - ''  # empty strings will be ignored
        - '--' # all string without "C:\" or "\\" at start will be ignored too for security reason
        - 'c:\a\a' # generates missing| string
        # - "c:\\Users\\Public\\*.log" # real string to process
        - "this\\is\\not\\recommended\\" # double quoating uses escape sequences
        # - 'c:\Users\Public\**\Desktop.ini' works, 8 files to control
        # - 'c:\Windows\Resources\**\aero\aero*.*' works too, you will get two files in 'c:\Windows\Resources\Themes\aero\'
        - 'c:\dev\shared_public\*.*' # typical test folder, should be provided by dev ops/developers

logwatch:
    enabled: yes
    
    sendall: no
    vista_api: no # this is RECOMMENDED settinsg

    logfile: # 
        - 'Application': crit context # allowed <crit|warn|all|off> + [context|nocontext]
        - 'System': warn nocontext 
        - 'Demo': all nocontext # allowed crit, warn, all, off
        - '': warn nocontext # allowed crit, warn, all, off
        - '*': off nocontext # allowed crit, warn, all, off, do not remove this

plugins:
    # scripts in plugin
    enabled: no

    # default value, you may disable all scripts in local with no
    player: '' # [-] when empty we wil use default value, i.e. our player

    # folders are scanned top -> down
    folders: 
        - core          # [-] folder with Check MK plugins(installation)
        - user          # [-] folder in ProgramData/CheckMK/agent/plugins
        - "c:\__mydlx"  # [-] absolute path here
        - "c:\__zx"     # 

    # example: mk_inventory.vbs
    # plugin is executed asynchronous
    # and is only updated every 3600 seconds
    # it may fail (timeout / error) up to 3 times before the last known data is discarded
    # we will look for a folder in core(Program Files/Check_mk/plugins), if not found in
    # ProgramData, if not found in __mdlx, etc/
    execution:
        # execution pattern for  windows-updates.vbs:   
        - pattern     : 'mk_inventory.vbs'  # [-] absolute or relative path. Better in ' ', wildcards [?] allowed
          async       : yes                 # [-] only for testing you may switch no   
          timeout     : 120                 # [-] after 120 seconds process will be killed.
          cache_age   : 3600                # [-] i do not know what is the hell
          retry_count : 3                   # [-]
          cmd_line    : ''                  # [-] command line
          description : 'In free form'      # [-] will be stored in the log

#        - pattern     : _invalid_ps_perf.ps1
#          timeout     : 20
        
#        - pattern     : '_invalid_*.ps1'
#          timeout     : 10
        
#        - pattern     : '_invalid_*'
#          timeout     : 30
    
    # When using the Check_MK Inventory plugin, it is a good idea to make the
    # plugin being executed asynchronous to prevent it from hooking up the
    # whole agent processing. Additionally it should have a execution timeout.
#        - pattern     : _invalid_mk_inventory.ps1
#          async       : yes
#          timeout     : 240
