# Copyright (C) 2019 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

[package]
name = "cmk-agent-ctl"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
async-std = { version = "1.13" }
async-trait = { version = "0.1" }
bincode = { version = "1.3" }  # binary serialisation, used by mailslot, can't be replaced with serde
clap = { version = "<4.5", features = ["derive"] }  # needs rustc >= 1.74
faccess = { version = "0.2" }
flate2 = { version = "1.1" }
flexi_logger = { version = "0.29", default-features = false }  # extension for log to allowe log redirection
gethostname = { version = "1.0.0" }
http = { version = "0.2" }
ipnet = { version = "2.11" }
log = { version = "0.4" }
nix = { version = "0.24" }
openssl = { version = "0.10", features = ["vendored"] }
os_info = { version = "3.10" }
rand = { version = "0.8" }
# Ideally, we would just use "rustls-tls-native-roots" instead of "native-tls" and
# "rustls-tls-manual-roots however, in SUP-10832, native-tls was ok with the custom CA of the
# customer, while rustls complained unfortunately, we couldn't find out why, so for now, we have to
# keep native-tls
reqwest = { version = "0.11", features = [
    "blocking",
    "json",
    "multipart",
    "native-tls",
    "rustls-tls-manual-roots",
] }
rpassword = { version = "7.3" }
rustls = { version = ">=0.21.7", features = ["dangerous_configuration"] }
rustls-pemfile = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_with = { version = "3.12" }
socket2 = { version = "0.5" }
string_enum = { version = "1.0.0" } # used to display and serialize ConnectionMode
tokio = { version = "1.43", features = ["full"] }
tokio-rustls = { version = "0.24" }
toml = { version = "0.8" }
uuid = { version = "1.15", features = ["v4"] }
x509-parser = { version = "0.13" }

[target.'cfg(windows)'.dependencies]
is_elevated = { version = "0.1" }
mail_slot = { version = "0.1" }  # windows mailslot api
winapi = { version = "0.3.9", features = ["processthreadsapi", "winsock2"] }

[dev-dependencies]
assert_cmd = { version = "<2.0.14" }  # needs rustc >= 1.73
lazy_static = { version = "1.5.0" }
predicates = { version = "3.1.3" }
tempfile = { version = "3.17.1" }

[profile.release]
opt-level = "z"  # Optimize for size.
