---
- name: hello world
  hosts: 127.0.0.1
  connection: local

  roles:
    - role: tribe29.checkmk.server
      vars:
        state: absent
        checkmk_server_edition: cee
    - "change-motd"
    - configure-apache

  tasks:
   - name: Disallow SSH password authentication
     lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication"
        line="PasswordAuthentication no"
        state=present
     become: yes
   - name: updates all packages
     ansible.builtin.apt:
       upgrade: dist
     become: true
