[project]
name = "cmk-astrein"
version = "1.0.0"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
astrein = "cmk.astrein.cli:main"

[tool.setuptools]
packages = ["cmk"]

[tool.bandit]
