type = "Component"
display_name = "Check & Agent Plugins"
has_support_component = true
members_required = 15
description = """
- Includes linux agent, special agents and agent plugins
- Includes Github pull request process:
  - Process for receipt of Github pull requests exists.
  - Pull requests are processed continuously
  - The open pull requests are decreasing and we can hold a low level
- Includes Logwatch
"""
