[project]
name = "cmk-plugin-apis"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint.per-file-ignores]
"cmk/server_side_programs/**/_vcrtrace" = [
  "A002", # unused args. We're following protocols.
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.bandit]
